import java.awt.*;

import Yourdon.*;
import symantec.itools.awt.InvisibleHTMLLink;
import symantec.itools.awt.RadioButtonGroupPanel;
import symantec.itools.awt.ComboBox;

public class EditarEventoDialog extends Dialog
{
    protected ListaEntidades entidades;
    protected Evento evento;
	public EditarEventoDialog(Frame parent, String title, boolean modal)
	{
		this(parent, modal);
		setTitle(title);
	}
    public EditarEventoDialog (Frame parent, ListaEntidades entidades, Evento evento)
    {
        this(parent, true);

        int         total;
        Entidade    entidade;

        this.evento = evento;
        this.entidades = entidades;

        this.setTitle(this.getTitle() + evento.getDescricao());

        // Carregar a lista com as entidades
        total = entidades.getQuantidade();
        for (int indice=0; indice<total; indice++)
        {
            entidade = entidades.getEntidade(indice);
            choice_entidades.add(entidade.getDescricao());
        }

        entidade = evento.getEntidade();
        if (entidade == null)
        {
            // É um evento temporal
            radioButton_entidade.setState(false);
            radioButton_temporal.setState(true);
            choice_entidades.setEnabled(false);
        }
        else
        {
            // É um evento de uma entidade
            choice_entidades.select(entidade.getDescricao());
            radioButton_entidade.setState(true);
            radioButton_temporal.setState(false);
            choice_entidades.setEnabled(true);
        }

        textField_evento.setText(evento.getDescricao());
        textField_estimulo.setText(evento.getEstimulo());
        textField_resposta.setText(evento.getResposta());
        // ...


    }
	public EditarEventoDialog(Frame parent, boolean modal)
	{
		super(parent, modal);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setVisible(false);
		setSize(522,194);
		setBackground(new Color(12632256));
		setEnabled(false);
		radioButtonGroupPanel1 = new symantec.itools.awt.RadioButtonGroupPanel();
		try {
			radioButtonGroupPanel1.setBorderColor(new java.awt.Color(12632256));
		}
		catch(java.beans.PropertyVetoException e) { }
		radioButtonGroupPanel1.setLayout(null);
		radioButtonGroupPanel1.setBounds(5,5,108,55);
		add(radioButtonGroupPanel1);
		radioButton_temporal = new java.awt.Checkbox("Temporal");
		radioButton_temporal.setBounds(1,3,96,18);
		radioButtonGroupPanel1.add(radioButton_temporal);
		radioButton_entidade = new java.awt.Checkbox("da Entidade");
		radioButton_entidade.setBounds(1,23,91,21);
		radioButtonGroupPanel1.add(radioButton_entidade);
		buttonlabel1 = new java.awt.Button();
		buttonlabel1.setLabel("Evento");
		buttonlabel1.setBounds(7,62,168,22);
		buttonlabel1.setBackground(new Color(12632256));
		add(buttonlabel1);
		buttonlabel1.setEnabled(false);
		labelbutton2 = new java.awt.Button();
		labelbutton2.setLabel("Estímulo");
		labelbutton2.setBounds(175,62,168,22);
		labelbutton2.setBackground(new Color(12632256));
		add(labelbutton2);
		labelbutton2.setEnabled(false);
		buttonlabel3 = new java.awt.Button();
		buttonlabel3.setLabel("Resposta");
		buttonlabel3.setBounds(343,62,167,22);
		buttonlabel3.setBackground(new Color(12632256));
		add(buttonlabel3);
		buttonlabel3.setEnabled(false);
		OKbutton = new java.awt.Button();
		OKbutton.setLabel("OK");
		OKbutton.setBounds(138,165,75,20);
		OKbutton.setBackground(new Color(12632256));
		add(OKbutton);
		Cancelarbutton = new java.awt.Button();
		Cancelarbutton.setLabel("Cancelar");
		Cancelarbutton.setBounds(223,165,75,20);
		Cancelarbutton.setBackground(new Color(12632256));
		add(Cancelarbutton);
		Ajudabutton = new java.awt.Button();
		Ajudabutton.setLabel("Ajuda");
		Ajudabutton.setBounds(308,165,75,20);
		Ajudabutton.setBackground(new Color(12632256));
		add(Ajudabutton);
		choice_entidades = new java.awt.Choice();
		add(choice_entidades);
		choice_entidades.setBounds(115,30,168,24);
		textField_evento = new java.awt.TextArea("",0,0,TextArea.SCROLLBARS_NONE);
		textField_evento.setBounds(10,85,165,65);
		add(textField_evento);
		textField_estimulo = new java.awt.TextArea("",0,0,TextArea.SCROLLBARS_NONE);
		textField_estimulo.setBounds(175,85,165,65);
		add(textField_estimulo);
		textField_resposta = new java.awt.TextArea("",0,0,TextArea.SCROLLBARS_NONE);
		textField_resposta.setBounds(340,85,165,65);
		add(textField_resposta);
		setTitle("Editar evento: ");
		//}}

		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		OKbutton.addActionListener(lSymAction);
		Cancelarbutton.addActionListener(lSymAction);
		SymItem lSymItem = new SymItem();
		radioButton_temporal.addItemListener(lSymItem);
		radioButton_entidade.addItemListener(lSymItem);
		SymFocus aSymFocus = new SymFocus();
		textField_evento.addFocusListener(aSymFocus);
		textField_estimulo.addFocusListener(aSymFocus);
		textField_resposta.addFocusListener(aSymFocus);
		Ajudabutton.addActionListener(lSymAction);
		//}}
	}
	
	public void addNotify()
	{
  	    // Record the size of the window prior to calling parents addNotify.
	    Dimension d = getSize();

		super.addNotify();

		if (fComponentsAdjusted)
			return;

		// Adjust components according to the insets
		setSize(insets().left + insets().right + d.width, insets().top + insets().bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(insets().left, insets().top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}

    // Used for addNotify check.
	boolean fComponentsAdjusted = false;

/*
	public EditarEventoDialog(Frame parent, String title, boolean modal)
	{
		this(parent, modal);
		setTitle(title);
	}
*/

	//{{DECLARE_CONTROLS
	symantec.itools.awt.RadioButtonGroupPanel radioButtonGroupPanel1;
	java.awt.Checkbox radioButton_temporal;
	java.awt.Checkbox radioButton_entidade;
	java.awt.Button buttonlabel1;
	java.awt.Button labelbutton2;
	java.awt.Button buttonlabel3;
	java.awt.Button OKbutton;
	java.awt.Button Cancelarbutton;
	java.awt.Button Ajudabutton;
	java.awt.Choice choice_entidades;
	java.awt.TextArea textField_evento;
	java.awt.TextArea textField_estimulo;
	java.awt.TextArea textField_resposta;
	//}}

	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == EditarEventoDialog.this)
				EditarEventoDialog_WindowClosing(event);
		}
	}
	
	void EditarEventoDialog_WindowClosing(java.awt.event.WindowEvent event)
	{
		setVisible(false);
	}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == OKbutton)
				OKbutton_ActionPerformed(event);
			else if (object == Cancelarbutton)
				Cancelarbutton_ActionPerformed(event);
			else if (object == Ajudabutton)
				Ajudabutton_ActionPerformed(event);
		}
	}

	void OKbutton_ActionPerformed(java.awt.event.ActionEvent event)
	{
	    int aux;
	    if (radioButton_temporal.getState())
	        evento.setEntidade(null);
	    else
	    {
	        aux =choice_entidades.getSelectedIndex(); 
	        evento.setEntidade(entidades.getEntidade(aux)); 
	    }   
	    evento.setDescricao(textField_evento.getText());
        evento.setEstimulo(textField_estimulo.getText());
        evento.setResposta(textField_resposta.getText());

		// to do: code goes here.

		//{{CONNECTION
		// Disable the Dialog
		setEnabled(false);
		//}}
		dispose();
	}

	void Cancelarbutton_ActionPerformed(java.awt.event.ActionEvent event)
	{
        setEnabled(false);
		// to do: code goes here.
		dispose();
	}

	class SymItem implements java.awt.event.ItemListener
	{
		public void itemStateChanged(java.awt.event.ItemEvent event)
		{
			Object object = event.getSource();
			if (object == radioButton_temporal)
				radioButtonTemporal_ItemStateChanged(event);
			else if (object == radioButton_entidade)
				radioButtonEntidade_ItemStateChanged(event);
		}
	}

	void radioButtonTemporal_ItemStateChanged(java.awt.event.ItemEvent event)
	{
	    if (radioButton_temporal.getState())
            choice_entidades.enable(false);
        else
            choice_entidades.enable(true);
	}

	void radioButtonEntidade_ItemStateChanged(java.awt.event.ItemEvent event)
	{
	    if (radioButton_entidade.getState())
	    {
            choice_entidades.enable(true);
            choice_entidades.requestFocus();
        }
        else
            choice_entidades.enable(false);
	}

	class SymFocus extends java.awt.event.FocusAdapter
	{
		public void focusLost(java.awt.event.FocusEvent event)
		{
			Object object = event.getSource();
			if (object == textField_evento)
				textFieldEvento_FocusLost(event);
			else if (object == textField_estimulo)
				textFieldEstimulo_FocusLost(event);
			else if (object == textField_resposta)
				textFieldResposta_FocusLost(event);
		}

		public void focusGained(java.awt.event.FocusEvent event)
		{
			Object object = event.getSource();
			if (object == textField_evento)
				textFieldEvento_FocusGained(event);
			else if (object == textField_estimulo)
				textFieldEstimulo_FocusGained(event);
			else if (object == textField_resposta)
				textFieldResposta_FocusGained(event);
		}
	}

	void textFieldEvento_FocusGained(java.awt.event.FocusEvent event)
	{
        textField_evento.selectAll();
	}

	void textFieldEvento_FocusLost(java.awt.event.FocusEvent event)
	{
        textField_evento.select(0,0);
	}

	void textFieldEstimulo_FocusGained(java.awt.event.FocusEvent event)
	{
        textField_estimulo.selectAll();
	}

	void textFieldEstimulo_FocusLost(java.awt.event.FocusEvent event)
	{
        textField_estimulo.select(0,0);
	}

	void textFieldResposta_FocusGained(java.awt.event.FocusEvent event)
	{
        textField_resposta.selectAll();
	}

	void textFieldResposta_FocusLost(java.awt.event.FocusEvent event)
	{
        textField_resposta.select(0,0);
	}

	void Ajudabutton_ActionPerformed(java.awt.event.ActionEvent event)
	{
        try
        {
            Runtime.getRuntime().exec("winhelp PowerCase.hlp");
        }
        catch (java.io.IOException e) {}
	}
    public void setVisible(boolean b)
	{
		if(b)
		{
			Rectangle bounds = getParent().getBounds();
			Rectangle abounds = getBounds();
	
			setLocation(bounds.x + (bounds.width - abounds.width)/ 2,
				 bounds.y + (bounds.height - abounds.height)/2);
		}
		super.setVisible(b);
	}
}

