/*
	A basic extension of the java.awt.Dialog class
 */

import java.awt.*;
import java.net.*;
import java.io.*;

import Yourdon.*;
public class EditarProcessoDialog extends Dialog
{
    protected void abrir ()
    {
        textField_descricao.requestFocus();
    }
    protected void fechar ()
    {
        this.dispose();
    }
    protected Processo processo;
    protected void ok ()
    {
        if (processo.pai != null)
        {
            try
            {
                processo.setNumero(Integer.parseInt(textField_numero.getText()));
            }
            catch (NumberFormatException e)
            {
                getToolkit().beep();
            }
        }
        processo.setDescricao(textField_descricao.getText());
    }
    public EditarProcessoDialog (Frame parent, Processo processo)
    {
        this(parent, true);

        this.processo = processo;

        if (processo.pai == null)
        {
            textField_numero.setEditable(false);
            this.setTitle(this.getTitle() + processo.getDescricao());
        }
        else
            this.setTitle(this.getTitle() + processo.getNomeCompleto());            

        textField_descricao.setText(processo.getDescricao());
        textField_numero.setText(String.valueOf(processo.getNumero()));

    }
	public EditarProcessoDialog(Frame parent, boolean modal)
	{
		super(parent, modal);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(null);
		setVisible(false);
		setSize(329,104);
		setBackground(new Color(12632256));
		label1 = new java.awt.Label("Nome do processo:");
		label1.setBounds(70,15,108,13);
		add(label1);
		textField_descricao = new java.awt.TextField();
		textField_descricao.setBounds(70,30,249,20);
		add(textField_descricao);
		button_ok = new java.awt.Button();
		button_ok.setLabel("Ok");
		button_ok.setBounds(40,70,75,20);
		button_ok.setBackground(new Color(12632256));
		add(button_ok);
		button_ajuda = new java.awt.Button();
		button_ajuda.setLabel("Ajuda");
		button_ajuda.setBounds(125,70,75,20);
		button_ajuda.setBackground(new Color(12632256));
		add(button_ajuda);
		button_cancelar = new java.awt.Button();
		button_cancelar.setLabel("Cancelar");
		button_cancelar.setBounds(210,70,75,20);
		button_cancelar.setBackground(new Color(12632256));
		add(button_cancelar);
		textField_numero = new java.awt.TextField();
		textField_numero.setBounds(10,30,50,20);
		add(textField_numero);
		label2 = new java.awt.Label("Número:");
		label2.setBounds(10,15,50,13);
		add(label2);
		setTitle("Editar processo: ");
		setResizable(false);
		//}}

		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		button_cancelar.addActionListener(lSymAction);
		button_ok.addActionListener(lSymAction);
		button_ajuda.addActionListener(lSymAction);
		SymFocus aSymFocus = new SymFocus();
		textField_descricao.addFocusListener(aSymFocus);
		textField_numero.addFocusListener(aSymFocus);
		//}}
	}
	
	public void addNotify()
	{
  	    // Record the size of the window prior to calling parents addNotify.
	    Dimension d = getSize();

		super.addNotify();

		if (fComponentsAdjusted)
			return;

		// Adjust components according to the insets
		setSize(insets().left + insets().right + d.width, insets().top + insets().bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(insets().left, insets().top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}

    // Used for addNotify check.
	boolean fComponentsAdjusted = false;


	public EditarProcessoDialog(Frame parent, String title, boolean modal)
	{
		this(parent, modal);
		setTitle(title);
	}

    /**
     * Shows or hides the component depending on the boolean flag b.
     * @param b  if true, show the component; otherwise, hide the component.
     * @see java.awt.Component#isVisible
     */
    public void setVisible(boolean b)
	{
		if(b)
		{
			Rectangle bounds = getParent().getBounds();
			Rectangle abounds = getBounds();
	
			setLocation(bounds.x + (bounds.width - abounds.width)/ 2,
				 bounds.y + (bounds.height - abounds.height)/2);
		}
		super.setVisible(b);
	}

	//{{DECLARE_CONTROLS
	java.awt.Label label1;
	java.awt.TextField textField_descricao;
	java.awt.Button button_ok;
	java.awt.Button button_ajuda;
	java.awt.Button button_cancelar;
	java.awt.TextField textField_numero;
	java.awt.Label label2;
	//}}

	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowOpened(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == EditarProcessoDialog.this)
				EditarProcessoDialog_WindowOpened(event);
		}

		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == EditarProcessoDialog.this)
				EditarProcessoDialog_WindowClosing(event);
		}
	}
	
	void EditarProcessoDialog_WindowClosing(java.awt.event.WindowEvent event)
	{
		setVisible(false);
	}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == button_cancelar)
				buttonCancelar_ActionPerformed(event);
			else if (object == button_ok)
				buttonOk_ActionPerformed(event);
			else if (object == button_ajuda)
				buttonAjuda_ActionPerformed(event);
		}
	}

	void buttonCancelar_ActionPerformed(java.awt.event.ActionEvent event)
	{
        this.fechar();
	}

	void buttonOk_ActionPerformed(java.awt.event.ActionEvent event)
	{
		this.ok();
		this.fechar();
	}

	void EditarProcessoDialog_WindowOpened(java.awt.event.WindowEvent event)
	{
        this.abrir();
	}

	void buttonAjuda_ActionPerformed(java.awt.event.ActionEvent event)
	{
        try
        {
            Runtime.getRuntime().exec("winhelp PowerCase.hlp");
        }
        catch (java.io.IOException e) {}
	}

	class SymFocus extends java.awt.event.FocusAdapter
	{
		public void focusLost(java.awt.event.FocusEvent event)
		{
			Object object = event.getSource();
			if (object == textField_descricao)
				textFieldDescricao_FocusLost(event);
			else if (object == textField_numero)
				textFieldNumero_FocusLost(event);
		}

		public void focusGained(java.awt.event.FocusEvent event)
		{
			Object object = event.getSource();
			if (object == textField_descricao)
				textFieldDescricao_FocusGained(event);
			else if (object == textField_numero)
				textFieldNumero_FocusGained(event);
		}
	}

	void textFieldDescricao_FocusGained(java.awt.event.FocusEvent event)
	{
        textField_descricao.selectAll();
	}

	void textFieldNumero_FocusGained(java.awt.event.FocusEvent event)
	{
        textField_numero.selectAll();
	}

	void textFieldDescricao_FocusLost(java.awt.event.FocusEvent event)
	{
        textField_descricao.select(0,0);
	}

	void textFieldNumero_FocusLost(java.awt.event.FocusEvent event)
	{
        textField_numero.select(0,0);
	}
}
